@baseUrl = https://localhost:5001
@authToken = {{login.response.body.data[0].authToken}}
@clientId = {{create.response.body.data[0]._id}}
@userId = {{login.response.body.data[0]._id}}
@refreshToken = {{login.response.body.data[0].refreshToken}}

###
# @name login
// --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
// Login
// --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
POST {{baseUrl}}/auth/login HTTP/1.1
content-type: application/json

{
    "email": "andy@mktgbuddy.com",
    "password": "Psion005"
}

###
# @name create
// --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
// create
// --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
POST {{baseUrl}}/clients HTTP/1.1
content-type: application/json
token: {{authToken}}

{
    "name": "Code test client - not shared",
    "clientPrefix": "CTC2"
}

###
# @name read
// --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
// read
// --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
GET {{baseUrl}}/clients HTTP/1.1
token: {{authToken}}

###
# @name readOne
// --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
// read
// --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
GET {{baseUrl}}/clients/6717c19d576c1d9c96d88388 HTTP/1.1
token: {{authToken}}

###
# @name readOneFull
// --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
// read
// --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
GET {{baseUrl}}/clients/6717c19d576c1d9c96d88388/full HTTP/1.1
token: {{authToken}}

###
# @name getLogoForClient
// --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
// read
// --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
GET {{baseUrl}}/client/6717c19d576c1d9c96d88388/backgroundLogo HTTP/1.1
token: {{authToken}}

###
# @name update
// --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
// update
// --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
PATCH {{baseUrl}}/clients/670001ce0531793fafbfbf46 HTTP/1.1
token: {{authToken}}
content-type: application/json

{
    "clientPrefix": "CTC2"
}

###
# @name removeShare
// --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
// update
// --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
PATCH {{baseUrl}}/clients/670001ce0531793fafbfbf46/removeShare HTTP/1.1
token: {{authToken}}
content-type: application/json

{
    "clientPrefix": "CTC2"
}

###
# @name delete
// --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
// delete
// --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
DELETE  {{baseUrl}}/clients/670001ce0531793fafbfbf46
token: {{authToken}}