@baseUrl = https://localhost:5001
@authToken = {{login.response.body.data[0].authToken}}
@refreshToken = {{login.response.body.data[0].refreshToken}}

###
# @name login
// --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
// Login
// --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
POST {{baseUrl}}/auth/login HTTP/1.1
content-type: application/json

{
    "email": "andy@mktgbuddy.com",
    "password": "Psion005"
}

###
# @name create
// --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
// create
// --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
POST {{baseUrl}}/dashboards HTTP/1.1
content-type: application/json
token: {{authToken}}

{
    "name": "My 1st dashboard",
    "client": "6717c19d576c1d9c96d88388"
}

###
# @name read
// --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
// read
// --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
GET {{baseUrl}}/dashboards HTTP/1.1
token: {{authToken}}


###
# @name readOneFull
// --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
// read
// --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
GET {{baseUrl}}/dashboards/6722d068df5051ca83ba0d89/full HTTP/1.1
token: {{authToken}}

###
# @name update
// --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
// update
// --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
PATCH {{baseUrl}}/dashboards/6722d068df5051ca83ba0d89 HTTP/1.1
token: {{authToken}}
content-type: application/json

{
   "page": [
        {
          "name": "Title",
          "title": "Marketing update",
          "subTitle": "CONFIDENTIAL, internal use only",
          "type": "Title",
          "options": {
            "titleIsHidden": false,
            "isHidden": false
          },
          "tile": [],
          "_id": "6722ca5c9afff0f77f4714a3"
        },
        {
          "name": "CRM",
          "title": "companies and contacts",
          "subTitle": "Growth in accurate data",
          "type": "Layout",
          "options": {
            "titleIsHidden": false,
            "isHidden": false
          },
          "tile": [{
            "title": "Hello",
            "position": {
              "x": 0,
              "y": 0,
              "width": 1,
              "height": 1
            },
            "integration": "6717c2050d2c1a36543ae0cd",
            "integrationObject": "company",
            "integrationTile": "totalCompanies"
          }],
          "_id": "672ab6530fce0b418ad64f00"
        },
        {
          "name": "New page",
          "title": "New page",
          "subTitle": "Sub-title",
          "type": "Layout",
          "options": {
            "titleIsHidden": false,
            "isHidden": true
          },
          "tile": [],
          "_id": "672aa8430fce0b418ad64c31"
        }
      ]
}

###
# @name delete
// --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
// delete
// --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
DELETE  {{baseUrl}}/dashboards/6722be1dfbe39f19c6b3c740
token: {{authToken}}