@baseUrl = https://localhost:5001
@authToken = {{login.response.body.data[0].authToken}}
@refreshToken = {{login.response.body.data[0].refreshToken}}

###
# @name login
// --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
// Login
// --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
POST {{baseUrl}}/auth/login HTTP/1.1
content-type: application/json

{
    "email": "andy@mktgbuddy.com",
    "password": "Psion005"
}

###
# @name create
// --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
// create
// --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
POST {{baseUrl}}/integrationApproval HTTP/1.1
content-type: application/json
token: {{authToken}}

{
    "client": "670001ce0531793fafbfbf46"
}

###
# @name read
// --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
// read
// --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
GET {{baseUrl}}/integrationApproval HTTP/1.1
token: {{authToken}}

###
# @name update
// --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
// update
// --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
PATCH {{baseUrl}}/integrationApproval/6717ff79e0dfa0727390035d HTTP/1.1
content-type: application/json

{
    "connection": {
        "authentication": {
            "authCode": "a2e77efca9f8a95eeca319a7a2523119"
        }
    }
}

###
# @name delete
// --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
// delete
// --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
DELETE  {{baseUrl}}/integrationApproval/67092280c98450b3e08a2fc2
token: {{authToken}}