@baseUrl = https://localhost:5001
@userId = {{login.response.body.data[0]._id}}
@authToken = {{login.response.body.data[0].authToken}}
@refreshToken = {{login.response.body.data[0].refreshToken}}

# @name login
// --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
// Login
// --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
POST {{baseUrl}}/auth/login HTTP/1.1
content-type: application/json

{
    "email": "code_primary_user@mktgbuddy.com",
    "password": "Code99"
}

###
# @name create
// --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
// create
// --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
POST {{baseUrl}}/users HTTP/1.1
content-type: application/json

{
    "email": "code_primary_user@mktgbuddy.com",
    "password": "Code99",
    "options": {
        "isSuperAdmin": true
    }

}

###
# @name read
// --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
// read
// --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
GET {{baseUrl}}/users HTTP/1.1
token: {{authToken}}

###
# @name update
// --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
// update
// --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
PATCH {{baseUrl}}/users/{{userId}} HTTP/1.1
token: {{authToken}}
content-type: application/json

{
    "firstName": "Code",
    "lastName": "Coder",
    "options": {
        "isEnabled": false
    }
}

###
# @name delete
// --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
// delete
// --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
DELETE  {{baseUrl}}/users/{{userId}}
token: {{authToken}}