@baseUrl = https://localhost:5001
@authToken = {{login.response.body.data[0].authToken}}
@refreshToken = {{login.response.body.data[0].refreshToken}}

###
# @name login
// --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
// Login
// --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
POST {{baseUrl}}/auth/login HTTP/1.1
content-type: application/json

{
    "email": "andy@mktgbuddy.com",
    "password": "Psion005"
}

###
# @name create
// --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
// create
// --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
POST {{baseUrl}}/integrations HTTP/1.1
content-type: application/json
token: {{authToken}}

{
    "client": "670001ce0531793fafbfbf46",
    "integrationPartner": "hubSpot",
    "authentication": {
        "method": "Email",
         "status": "Send for approval",
        "sendTo": {
            "email": {
                "address": "mistavia@mac.com"
            }
        }
    }
}

###
# @name read
// --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
// read
// --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
GET {{baseUrl}}/integrations?full HTTP/1.1
token: {{authToken}}

###
# @name testIntegration
// --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
// read
// --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
GET {{baseUrl}}/integrations/6717c2050d2c1a36543ae0cd/test HTTP/1.1
token: {{authToken}}

###
# @name executeDataFetch
// --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
// read
// --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# GET {{baseUrl}}/integrations/6717c2050d2c1a36543ae0cd/fetch?object=company&tile=totalCompanies&year=2024&month=10&filter=%7B%22propertyName%22%3A%22work_with%22%2C%22operator%22%3A%22CONTAINS_TOKEN%22%2C%22value%22%3A%22Grey%22%7D HTTP/1.1
GET {{baseUrl}}/integrations/6717c2050d2c1a36543ae0cd/fetch?object=company&tile=totalCompanies
token: {{authToken}}

###
# @name readOneFull
// --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
// read
// --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
GET {{baseUrl}}/integrations/6717c2050d2c1a36543ae0cd/full HTTP/1.1
token: {{authToken}}

###
# @name readWithFilter
// --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
// read
// --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
GET {{baseUrl}}/integrations?filterFields=name&filter=2 HTTP/1.1
token: {{authToken}}

###
# @name update
// --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
// update
// --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
PATCH {{baseUrl}}/integrations/6716ce523b4576898d41e2e4 HTTP/1.1
token: {{authToken}}
content-type: application/json

{
    "connection": {
        "authentication": {
            "authCode": "eu1-77bb-c1fc-45e1-b061-49d175d79478"
        }
    }
}

###
# @name delete
// --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
// delete
// --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
DELETE  {{baseUrl}}/integrations/67092280c98450b3e08a2fc2
token: {{authToken}}