@baseUrl = https://localhost:5001

###
// --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
// integrationData
// --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
GET {{baseUrl}}/integrationPartners HTTP/1.1