#@baseUrl = https://localhost:5001

@baseUrl = https://api.mktgbuddy.com
###
// --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
// integrationData
// --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
GET {{baseUrl}}/integrationPartners HTTP/1.1