# @baseUrl = https://localhost:5001
@baseUrl = http://plankton-app-7mjie.ondigitalocean.app

###
// --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
// integrationData
// --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
GET {{baseUrl}}/integrationPartners HTTP/1.1