@baseUrl = https://localhost:5001

###
// --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
// integrationData
// --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
GET {{baseUrl}}/models/integration HTTP/1.1
